### ISSUE TITLE
 アクセス権のないユーザーがDiffにアクセスしてきた場合

### ISSUE THREAD

**Issue by Kinoshita0623** [yumekiti/diffweb#16]
Diffへのアクセス権のないユーザーがDiffへアクセスしてきた場合どうするのか。
## Diffへのアクセス権がないとは
* Diffのメンバーではないユーザー
* ログインしていないユーザー

## 候補
* 401を返してログイン画面へ遷移する
* 404を返す

**Comment by yumekiti** [comment]
404を表示しホーム画面へ移動ボタンをおいたら良いと思います

**Comment by Kinoshita0623** [comment]
了解です。
